import { NativeModule, requireNativeModule } from "expo";

import type {
  Company,
  CrispLogLevel,
  CrispSessionEventColors,
  EmptyPayload,
  LogReceivedPayload,
  MessageContent,
  MessagePayload,
  NotificationHandleOptions,
  NotificationHandleResult,
  NotificationReceivedPayload,
  NotificationStatus,
  NotificationTappedPayload,
  SessionEvent,
  SessionLoadedPayload,
  TokenRegistrationResult,
} from "./ExpoCrispSdk.types";

type ExpoCrispSdkEvents = {
  /**
   * Emitted when the Crisp session has fully loaded.
   * @param params - Contains the session identifier
   */
  onSessionLoaded: (params: SessionLoadedPayload) => void;

  /**
   * Emitted when the chat widget is opened by the user.
   */
  onChatOpened: (params: EmptyPayload) => void;

  /**
   * Emitted when the chat widget is closed by the user.
   */
  onChatClosed: (params: EmptyPayload) => void;

  /**
   * Emitted when the visitor sends a message.
   * @param params - Contains the message details
   */
  onMessageSent: (params: MessagePayload) => void;

  /**
   * Emitted when a message is received from an operator.
   * @param params - Contains the message details
   */
  onMessageReceived: (params: MessagePayload) => void;

  /**
   * Emitted when a log message is generated by the native SDK.
   * Requires setLogLevel to be called to enable logging.
   * @param params - Contains the log entry details
   */
  onLogReceived: (params: LogReceivedPayload) => void;

  /**
   * Emitted when a Crisp notification is received while app is in foreground.
   * Only fires in app-managed mode when handleNotification() is called.
   * @param params - Contains the notification data and display status
   */
  onNotificationReceived: (params: NotificationReceivedPayload) => void;

  /**
   * Emitted when user taps a Crisp notification.
   * Fires in both SDK-managed and app-managed modes.
   * @param params - Contains the notification data and session ID
   */
  onNotificationTapped: (params: NotificationTappedPayload) => void;
};

declare class ExpoCrispSdkModule extends NativeModule<ExpoCrispSdkEvents> {
  // ============================================================================
  // Configuration
  // ============================================================================

  /**
   * Initialize the Crisp SDK with your website ID.
   * Must be called once at app startup before using any other methods.
   *
   * @param websiteId - Your Website ID from the Crisp Dashboard
   * @see https://docs.crisp.chat/guides/chatbox-sdks/ios-sdk/#configure-crisp
   */
  configure(websiteId: string): void;

  /**
   * Set a token for session persistence across app reinstalls and devices.
   * Use this to maintain chat history when a user logs in.
   *
   * @param tokenId - Unique identifier (e.g., user ID), or `null` to clear
   * @example
   * // On login
   * ExpoCrispSdk.setTokenId(user.id);
   * // On logout
   * ExpoCrispSdk.setTokenId(null);
   */
  setTokenId(tokenId: string | null): void;

  /**
   * Set the minimum log level for SDK logging.
   * Logs at or above this level will be emitted via the onLogReceived event.
   * Default level is WARN.
   *
   * @param level - Minimum log level to emit
   * @example
   * // Enable debug logging
   * ExpoCrispSdk.setLogLevel(CrispLogLevel.DEBUG);
   *
   * // Only show errors
   * ExpoCrispSdk.setLogLevel(CrispLogLevel.ERROR);
   */
  setLogLevel(level: CrispLogLevel): void;

  // ============================================================================
  // User Information
  // ============================================================================

  /**
   * Set the user's email address for identification in the chat.
   *
   * @param email - User's email address
   * @param signature - Optional HMAC-SHA256 signature for email verification
   * @see https://docs.crisp.chat/guides/chatbox-sdks/ios-sdk/#set-user-email
   */
  setUserEmail(email: string, signature?: string | null): void;

  /**
   * Set the user's display name shown in the chat.
   *
   * @param name - User's nickname or display name
   */
  setUserNickname(name: string): void;

  /**
   * Set the user's phone number.
   *
   * @param phone - Phone number (E.164 format recommended, e.g., "+1234567890")
   */
  setUserPhone(phone: string): void;

  /**
   * Set the user's company information.
   *
   * @param company - Company details including name, URL, employment, and location
   * @example
   * ExpoCrispSdk.setUserCompany({
   *   name: "Acme Inc",
   *   url: "https://acme.com",
   *   employment: { title: "Engineer", role: "Development" },
   *   geolocation: { country: "France", city: "Paris" }
   * });
   */
  setUserCompany(company: Company): void;

  /**
   * Set the user's avatar image.
   *
   * @param url - URL to the user's avatar image
   */
  setUserAvatar(url: string): void;

  // ============================================================================
  // Session Data
  // ============================================================================

  /**
   * Store a custom string value in the session data.
   * Visible to operators in the Crisp dashboard.
   *
   * @param key - Data key
   * @param value - String value to store
   */
  setSessionString(key: string, value: string): void;

  /**
   * Store a custom boolean value in the session data.
   * Visible to operators in the Crisp dashboard.
   *
   * @param key - Data key
   * @param value - Boolean value to store
   */
  setSessionBool(key: string, value: boolean): void;

  /**
   * Store a custom integer value in the session data.
   * Visible to operators in the Crisp dashboard.
   *
   * @param key - Data key
   * @param value - Integer value to store
   */
  setSessionInt(key: string, value: number): void;

  /**
   * Set a single segment to categorize the user.
   * Segments help organize users in the Crisp dashboard.
   *
   * @param segment - Segment name (e.g., "premium", "trial")
   */
  setSessionSegment(segment: string): void;

  /**
   * Set multiple segments to categorize the user.
   *
   * @param segments - Array of segment names
   * @param overwrite - If true, replaces existing segments; if false, appends
   */
  setSessionSegments(segments: string[], overwrite?: boolean): void;

  /**
   * Get the current session identifier.
   *
   * @returns Promise resolving to the session ID, or null if not available
   */
  getSessionIdentifier(): Promise<string | null>;

  // ============================================================================
  // Events
  // ============================================================================

  /**
   * Track a single event in the user's chat timeline.
   * Events are visible to operators and help understand user actions.
   *
   * @param name - Event name (e.g., "Purchase completed")
   * @param color - Event color for visual categorization
   * @example
   * ExpoCrispSdk.pushSessionEvent("Checkout", CrispSessionEventColors.GREEN);
   */
  pushSessionEvent(name: string, color: CrispSessionEventColors): void;

  /**
   * Track multiple events in the user's chat timeline.
   *
   * @param events - Array of events with name and color
   * @example
   * ExpoCrispSdk.pushSessionEvents([
   *   { name: "Added to cart", color: CrispSessionEventColors.BLUE },
   *   { name: "Checkout started", color: CrispSessionEventColors.ORANGE }
   * ]);
   */
  pushSessionEvents(events: SessionEvent[]): void;

  // ============================================================================
  // Session Management
  // ============================================================================

  /**
   * Reset the current chat session.
   * Clears all session data and starts a fresh conversation.
   * Typically called on user logout.
   */
  resetSession(): void;

  // ============================================================================
  // UI
  // ============================================================================

  /**
   * Open the Crisp chat widget.
   * Presents the chat interface as a modal.
   */
  show(): void;

  /**
   * Open the helpdesk search interface.
   * Allows users to search through your knowledge base articles.
   */
  searchHelpdesk(): void;

  /**
   * Open a specific helpdesk article.
   *
   * @param id - Article slug or identifier
   * @param locale - Article locale (e.g., "en", "fr")
   * @param title - Optional article title for display
   * @param category - Optional category name for display
   */
  openHelpdeskArticle(
    id: string,
    locale: string,
    title?: string | null,
    category?: string | null,
  ): void;

  /**
   * Trigger an automated bot scenario.
   * Starts a predefined conversation flow configured in the Crisp dashboard.
   *
   * @param scenarioId - The scenario identifier from the Crisp dashboard
   */
  runBotScenario(scenarioId: string): void;

  // ============================================================================
  // Messages
  // ============================================================================

  /**
   * Display a message as operator in the local chatbox.
   * The message appears as if sent by an operator but is only shown locally.
   *
   * @param content - The message content to display
   *
   * @example
   * // Simple text message
   * ExpoCrispSdk.showMessage({ type: "text", text: "Hello! How can I help?" });
   *
   * @example
   * // Picker for user input
   * ExpoCrispSdk.showMessage({
   *   type: "picker",
   *   id: "rating",
   *   text: "How would you rate our service?",
   *   choices: [
   *     { value: "great", label: "Great!" },
   *     { value: "ok", label: "Okay" },
   *     { value: "poor", label: "Could be better" }
   *   ]
   * });
   */
  showMessage(content: MessageContent): void;

  // ============================================================================
  // Push Notifications
  // ============================================================================

  /**
   * Register device push token with Crisp.
   *
   * Use this in app-managed mode when you obtain tokens from your own
   * notification system (expo-notifications, react-native-firebase, etc.).
   *
   * @param token - APNs token (iOS, hex string) or FCM token (Android)
   * @returns Promise with registration result
   *
   * @example
   * // With expo-notifications
   * const { data: token } = await Notifications.getDevicePushTokenAsync();
   * const result = await ExpoCrispSdk.registerPushToken(token);
   * if (!result.success) {
   *   console.error('Failed to register:', result.message);
   * }
   *
   * @example
   * // With react-native-firebase
   * const token = await messaging().getToken();
   * await ExpoCrispSdk.registerPushToken(token);
   */
  registerPushToken(token: string): Promise<TokenRegistrationResult>;

  /**
   * Unregister current push token from Crisp.
   *
   * Call this before registering a new token on refresh to prevent
   * duplicate notifications.
   *
   * @returns Promise with success status
   *
   * @example
   * // On token refresh
   * messaging().onTokenRefresh(async (newToken) => {
   *   await ExpoCrispSdk.unregisterPushToken();
   *   await ExpoCrispSdk.registerPushToken(newToken);
   * });
   */
  unregisterPushToken(): Promise<{ success: boolean }>;

  /**
   * Get current push notification registration status.
   *
   * @returns Promise with current status
   *
   * @example
   * const status = await ExpoCrispSdk.getNotificationStatus();
   * if (!status.isRegistered) {
   *   // Prompt user to enable notifications
   * }
   */
  getNotificationStatus(): Promise<NotificationStatus>;

  /**
   * Check if a notification payload is from Crisp.
   *
   * This is a synchronous check for fast routing decisions.
   * Use this to route notifications in apps with multiple SDKs.
   *
   * Detection checks:
   * - `sender` field equals "crisp" (case-insensitive)
   * - `website_id` field is present
   * - `session_id` field is present
   *
   * WARNING: This check is NOT cryptographically secure. For security-sensitive
   * operations, verify notification content against your backend.
   *
   * @param payload - Notification data payload (remoteMessage.data)
   * @returns true if notification is from Crisp
   *
   * @example
   * messaging().onMessage(async remoteMessage => {
   *   if (ExpoCrispSdk.isCrispNotification(remoteMessage.data)) {
   *     await ExpoCrispSdk.handleNotification(remoteMessage.data);
   *   } else if (Intercom.isIntercomPush(remoteMessage)) {
   *     Intercom.handlePushMessage();
   *   } else {
   *     // Handle other notifications
   *   }
   * });
   */
  isCrispNotification(payload: Record<string, unknown> | null | undefined): boolean;

  /**
   * Forward a notification to Crisp for processing.
   *
   * Call this after verifying the notification is from Crisp using
   * `isCrispNotification()`.
   *
   * Behavior:
   * - SDK-managed mode: Logs warning, notification already handled
   * - App-managed mode: Processes notification, optionally displays
   *
   * @param payload - Notification data payload
   * @param options - Optional handling configuration
   * @returns Promise with handle result
   *
   * @example
   * // Let Crisp handle display
   * const result = await ExpoCrispSdk.handleNotification(payload);
   *
   * @example
   * // Handle display yourself (Android only)
   * const result = await ExpoCrispSdk.handleNotification(payload, {
   *   displayNotification: false
   * });
   * if (result.wasHandled) {
   *   // Show custom notification UI
   *   await Notifications.presentLocalNotificationAsync({
   *     title: 'New message from support',
   *     body: payload.message,
   *   });
   * }
   */
  handleNotification(
    payload: Record<string, unknown>,
    options?: NotificationHandleOptions,
  ): Promise<NotificationHandleResult>;
}

export default requireNativeModule<ExpoCrispSdkModule>("ExpoCrispSdk");
